wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/FlashEdison.json -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison-image-edison.ext4 -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison-image-edison.hddimg -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_dnx_fwr.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_dnx_osr.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-00-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-00.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-01-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-01.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-02-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-02.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-03-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-03.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-04-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-04.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-05-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-05.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-06-dfu.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/edison_ifwi-dbg-06.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/filter-dfu-out.js -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/flashall.bat -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/flashall.sh -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/helper/helper.html -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/helper/images/Edison-arduino-blink-led.png -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/helper/images/Edison-arduino.png -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/helper/images/Edison-breakout-board.png -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/ota_update.scr -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/package-list.txt -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-edison.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-edison.img -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-envs/edison-blankcdc.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-envs/edison-blankrndis.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-envs/edison-ifwi.bin -P /update || exit 1
wget --no-check-certificate http://neil-lakin.com/download/edison/fresh/u-boot-envs/edison-prod.bin -P /update || exit 1
