wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/FlashEdison.json -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison-image-edison.ext4 -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison-image-edison.hddimg -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_dnx_fwr.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_dnx_osr.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-00-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-00.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-01-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-01.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-02-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-02.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-03-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-03.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-04-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-04.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-05-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-05.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-06-dfu.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/edison_ifwi-dbg-06.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/filter-dfu-out.js -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/flashall.bat -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/flashall.sh -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/helper/helper.html -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/helper/images/Edison-arduino-blink-led.png -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/helper/images/Edison-arduino.png -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/helper/images/Edison-breakout-board.png -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/ota_update.scr -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/package-list.txt -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-edison.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-edison.img -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-envs/edison-blankcdc.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-envs/edison-blankrndis.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-envs/edison-ifwi.bin -P /update || exit 1
wget --no-check-certificate https://s3.amazonaws.com/kinetic-device-bootstrap/firmware/custom-30Oct2015/u-boot-envs/edison-prod.bin -P /update || exit 1
